# Generated by Django 4.2 on 2023-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
