# Generated by Django 4.2 on 2023-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.IntegerField(default=0),
        ),
    ]
