# Generated by Django 4.2 on 2023-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tag_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='tag', max_length=500),
            preserve_default=False,
        ),
    ]
